/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertRouteImport } from './routes/alert'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as PairRouteImport } from './routes/pair'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SosRouteImport } from './routes/sos'
import { Route as CallIndexRouteImport } from './routes/call.index'
import { Route as CallPeerIdRouteImport } from './routes/call.$peerId'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatPeerIdRouteImport } from './routes/chat.$peerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertRoute = AlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const CallIndexRoute = CallIndexRouteImport.update({
  id: '/call/',
  path: '/call/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallPeerIdRoute = CallPeerIdRouteImport.update({
  id: '/call/$peerId',
  path: '/call/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPeerIdRoute = ChatPeerIdRouteImport.update({
  id: '/chat/$peerId',
  path: '/chat/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/devices': typeof DevicesRoute
  '/nodes': typeof NodesRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/call/$peerId': typeof CallPeerIdRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/call/': typeof CallIndexRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/devices': typeof DevicesRoute
  '/nodes': typeof NodesRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/call/$peerId': typeof CallPeerIdRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/call': typeof CallIndexRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/devices': typeof DevicesRoute
  '/nodes': typeof NodesRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/call/$peerId': typeof CallPeerIdRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/call/': typeof CallIndexRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alert'
    | '/devices'
    | '/nodes'
    | '/pair'
    | '/settings'
    | '/sos'
    | '/call/$peerId'
    | '/chat/$peerId'
    | '/call/'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alert'
    | '/devices'
    | '/nodes'
    | '/pair'
    | '/settings'
    | '/sos'
    | '/call/$peerId'
    | '/chat/$peerId'
    | '/call'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/alert'
    | '/devices'
    | '/nodes'
    | '/pair'
    | '/settings'
    | '/sos'
    | '/call/$peerId'
    | '/chat/$peerId'
    | '/call/'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertRoute: typeof AlertRoute
  DevicesRoute: typeof DevicesRoute
  NodesRoute: typeof NodesRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRoute
  SosRoute: typeof SosRoute
  CallPeerIdRoute: typeof CallPeerIdRoute
  ChatPeerIdRoute: typeof ChatPeerIdRoute
  CallIndexRoute: typeof CallIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert': {
      id: '/alert'
      path: '/alert'
      fullPath: '/alert'
      preLoaderRoute: typeof AlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/': {
      id: '/call/'
      path: '/call'
      fullPath: '/call/'
      preLoaderRoute: typeof CallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$peerId': {
      id: '/call/$peerId'
      path: '/call/$peerId'
      fullPath: '/call/$peerId'
      preLoaderRoute: typeof CallPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$peerId': {
      id: '/chat/$peerId'
      path: '/chat/$peerId'
      fullPath: '/chat/$peerId'
      preLoaderRoute: typeof ChatPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertRoute: AlertRoute,
  DevicesRoute: DevicesRoute,
  NodesRoute: NodesRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRoute,
  SosRoute: SosRoute,
  CallPeerIdRoute: CallPeerIdRoute,
  ChatPeerIdRoute: ChatPeerIdRoute,
  CallIndexRoute: CallIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
